[profile.default]
src = "src"
out = "out"
libs = ["lib", "../../node_modules"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true

# Allow using inline assembly
evm_version = "cancun"

[rpc_endpoints]
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
inco = "${INCO_RPC_URL}"

[etherscan]
baseSepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
